sudo: required
language: ruby
cache: bundler
rvm:
- 2.5.1
services:
- postgresql
notifications:
  slack: patagonia-mara:xaEjhNnxt9qqXGyyqyGXUfDF
before_install:
- openssl aes-256-cbc -K $encrypted_231b5c201e7b_key -iv $encrypted_231b5c201e7b_iv
  -in master.key.enc -out config/master.key -d
- cp config/database.yml.example config/database.yml
- gem update --system
install:
- bin/bundle install --path vendor/bundle
before_script:
- bin/rake db:create RAILS_ENV=test
- bin/rake db:migrate RAILS_ENV=test
jobs:
  include:
  - stage: rspec
    script: bin/rake
  - stage: brakeman
    script: bundle exec brakeman
  - stage: bundler-audit
    script: bundle exec bundler-audit
